### Create Supplier Invoice with Items
# POST http://localhost:4004/odata/v2/dashboard

# GET http://localhost:4004/odata/v2/dashboard/Invoice(guid'0891c370-62dc-4cf0-a220-1d88686baa94')?$expand=to_InvoiceItem 


# GET Invoice(guid'731c1e63-7a0d-48b1-8572-729c3fb88e71')?$expand=to_InvoiceItem 
# Content-Type: application/json
# Content-ID: id-1762274582593-266
# sap-contextid-accept: header
# Accept: application/json
# Accept-Language: en-US
# DataServiceVersion: 2.0
# MaxDataServiceVersion: 2.0
# X-Requested-With: XMLHttpRequest
# Content-Length: 216

# {"purchaseOrder":"","poQuantityUnit":"","quantityPOUnit":0.00,"sup_InvoiceItem":"","supInvItemAmount":0,"Plant":"","ProductType":"","TaxJurisdiction":"","taxCode":"","__metadata":{"type":"DashboardService.InvoiceItem"}}
# --changeset_feff-f6a2-5ade
# Content-Type: application/http
# Content-Transfer-Encoding: binary

# POST Invoice HTTP/1.1
# sap-contextid-accept: header
# Accept: application/json
# Accept-Language: en-US
# DataServiceVersion: 2.0
# MaxDataServiceVersion: 2.0
# X-Requested-With: XMLHttpRequest
# Content-Type: application/json
# Content-ID: id-1762411167451-137
# Content-Length: 561

# {"fiscalYear":"2025","companyCode":"12","documentDate":"","postingDate":"","supInvParty":"","documentCurrency_code":"","invGrossAmount":"100","DocumentHeaderText":"","PaymentTerms":"","AccountingDocumentType":"","InvoicingParty":"test","statusFlag":"","to_InvoiceItem":[{"sup_InvoiceItem":"0010","purchaseOrder":"11111","purchaseOrderItem":"","referenceDocument":"","refDocFiscalYear":"","refDocItem":"","taxCode":"","documentCurrency_code":"","supInvItemAmount":"","poQuantityUnit":"PC","quantityPOUnit":"10","Plant":"","TaxJurisdiction":"","ProductType":""}]}

1
PATCH  http://localhost:33389/odata/v2/dashboard/Invoice('0891c370-62dc-4cf0-a220-1d88686baa94')
Content-Type: application/json

# {"fiscalYear":"2025","companyCode":"12","documentDate":"/Date(1595116800000)/","postingDate":"/Date(1595116800000)/","supInvParty":"","documentCurrency_code":"","invGrossAmount":"100","DocumentHeaderText":"","PaymentTerms":"","AccountingDocumentType":"","InvoicingParty":"test","statusFlag":"","to_InvoiceItem":[{"sup_InvoiceItem":"0010","purchaseOrder":"11111","purchaseOrderItem":"","referenceDocument":"","refDocFiscalYear":"","refDocItem":"","taxCode":"","documentCurrency_code":"","supInvItemAmount":"0.0","poQuantityUnit":"PC","quantityPOUnit":"10","Plant":"","TaxJurisdiction":"","ProductType":""}]}
{"fiscalYear":"2025","companyCode":"123","documentDate":"\/Date(1762387200000)\/","postingDate":"\/Date(1762413770846)\/","supInvParty":"","documentCurrency_code":"","invGrossAmount":"0.00","DocumentHeaderText":"","PaymentTerms":"","AccountingDocumentType":"","InvoicingParty":"","statusFlag":"","to_InvoiceItem":[{"sup_InvoiceItem":"","purchaseOrder":"111111","purchaseOrderItem":"","referenceDocument":"","refDocFiscalYear":"","refDocItem":"","taxCode":"","documentCurrency_code":"","supInvItemAmount":"0.0","poQuantityUnit":"","quantityPOUnit":"0.00","Plant":"","TaxJurisdiction":"","ProductType":""}]}

###
POST http://localhost:4004/odata/v4/dashboard/DashboardService.postInvoice
Content-Type: application/json

{
    "documentNumber": "5000000010",
    "netAmount": "$ 1600.00",
    "taxId": "12-5846832",
    "taxName": "Sales Tax:",
    "purchaseOrderNumber": "4500000011",
    "grossAmount": "$ 1600.00",
    "currencyCode": "CAD",
    "receiverContact": "Curtis V. Brown",
    "documentDate": "2025-02-05",
    "taxAmount": "$ 0.00",
    "taxRate": "0.0",
    "receiverName": "Standard Products",
    "receiverAddress": "3150 SW 9th Street Toronto, ON L5V 1X2 CANADA",
    "paymentTerms": "Due upon receipt",
    "senderAddress": "3451 NE Willoughby Blvd. Sturt, ON LV5 1X2 CANADA",
    "senderName": "Alfreds Futterkiste",
    "senderMail": "jibin.thomas@msitek.us",
    "dmsFolder": "spa-res:cmis:folderid:41y4Txs0ZaFMpWNMSVE4E5gfRdg1jg5UiAyeswYbbJM",
    "to_Item": [
        {
            "description": "Professional Service",
            "netAmount": "1600.00",
            "quantity": "100.00",
            "unitPrice": "16.00",
            "materialNumber": "2001",
            "unitOfMeasure": "PC"
        }
    ]
}

###
POST https://port4004-workspaces-ws-pu6id.us10.applicationstudio.cloud.sap/odata/v4/dashboard/Invoice(ID='c1b0ca2e-4999-4a97-9d32-e81800b95451',IsActiveEntity=false)/attachments HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en-US
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true

{"filename":"Frame 119.pdf",
"note": "test"}
--batch_id-1762801738477-95--
Group ID: $auto


###
POST http://localhost:46769/odata/v4/dashboard/Invoice(ID=c1b0ca2e-4999-4a97-9d32-e81800b95451,IsActiveEntity=false)/attachments
Content-Type: application/json
Accept: application/json

{
    "up__ID": "c1b0ca2e-4999-4a97-9d32-e81800b95451",
    "filename": "Frame 144.pdf",
    "note": "test"
}

###
GET http://localhost:46769/odata/v4/dashboard/Invoice(ID=c1b0ca2e-4999-4a97-9d32-e81800b95451,IsActiveEntity=false)/attachments

###
pos
GET https://yk2lt6xsylvfx4dz.launchpad.cfapps.us10.hana.ondemand.com/94d10e88-efc0-4403-ac6d-73d65521b2f0.hanaapp.zdashboard-1.0.0/odata/v4/dashboard/Invoice(ID=140ced70-683d-4aea-8548-3ba7b4ee1ddc,IsActiveEntity=true)
